name: Kotlin

on:
  pull_request:
    branches: [ "feature/test-migration" ]

jobs:
  setup:
    name: Sets Up the Build Server
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up gradle wrapper
        run: gradle wrapper
  test:
    needs: setup
    name: Run Unit Tests
    runs-on: macos-latest
    steps:
      - name: Unit tests
        run: bash ./gradlew test --stacktrace --warning-mode all
  androidTest:
    needs: setup
    name: Run Instrumented Unit Tests
    runs-on: macos-latest
    steps:
      - name: Run on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          profile: Nexus 6
          avd-name: test
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew tealiumlibrary:connectedCheck
          # TODO: instrumented tests need fixing, testing with just the tealiumlibrary module for now

    # Create APK. To download APK file, click on Artifacts within the Actions tab
  apk:
    needs: setup
    name: Generate APK
    runs-on: macos-latest
    steps:
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace --warning-mode all
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: mobile
          path: mobile/build/outputs/apk/debug/mobile-debug.apk