name: Kotlin

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up gradle wrapper
        run: gradle wrapper
      - name: Unit tests
        run: bash ./gradlew test --stacktrace --warning-mode all

    # Create APK. To download APK file, click on Artifacts within the Actions tab
#  apk:
#    name: Generate APK
#    runs-on: macos-latest
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Set up gradle wrapper
#        run: gradle wrapper
#      - name: Build debug APK
#        run: bash ./gradlew assembleDebug --stacktrace --warning-mode all
#      - name: Upload APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: mobile
#          path: mobile/build/outputs/apk/debug/mobile-debug.apk